const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.LayerEmpty,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Browser.Acts.Close
	];
};
self.C3_JsPropNameTable = [
	{quadrante1: 0},
	{quadrante3: 0},
	{quadrante2: 0},
	{quadrante4: 0},
	{Mouse: 0},
	{telaGeral: 0},
	{telaInicial: 0},
	{botaojogar: 0},
	{quadro: 0},
	{clicarporcos: 0},
	{botaovoltar: 0},
	{quadro5: 0},
	{clicarvacas: 0},
	{clicarpescador: 0},
	{clicarregador: 0},
	{clicarbeberagua: 0},
	{quadro6: 0},
	{clicarcrianças: 0},
	{quadro8: 0},
	{porco2: 0},
	{clicarACERTOU: 0},
	{clicarERROU: 0},
	{porcoACERTOU: 0},
	{porcoERROU: 0},
	{vaca2: 0},
	{vacaACERTOU: 0},
	{vacaERROU: 0},
	{pescador2: 0},
	{pescadorACERTOU: 0},
	{pescadorERROU: 0},
	{planta: 0},
	{plantaACERTOU: 0},
	{plantaERROU: 0},
	{agua: 0},
	{aguaACERTOU: 0},
	{aguaERROU: 0},
	{criancas: 0},
	{criancasACERTOU: 0},
	{criancasERROU: 0},
	{Texto_Acao: 0},
	{Áudio: 0},
	{botaosair: 0},
	{Navegador: 0},
	{botaoinfo: 0},
	{buttonMaker: 0},
	{Texto: 0},
	{Senóide: 0},
	{EXCLAMAÇÃO1: 0},
	{EXCLAMAÇÃO2: 0},
	{EXCLAMAÇÃO3: 0},
	{EXCLAMAÇÃO4: 0},
	{EXCLAMAÇÃO5: 0},
	{EXCLAMAÇÃO6: 0},
	{teste: 0},
	{beberfoiclicado: 0},
	{regadorfoiclicado: 0},
	{Pontuação: 0},
	{objetosDesaparecidos: 0},
	{porcosfoiclicado: 0},
	{vacasfoiclicado: 0},
	{pescadorfoiclicado: 0},
	{criancasfoiclicado: 0}
];

self.InstanceType = {
	quadrante1: class extends self.ISpriteInstance {},
	quadrante3: class extends self.ISpriteInstance {},
	quadrante2: class extends self.ISpriteInstance {},
	quadrante4: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	telaGeral: class extends self.ISpriteInstance {},
	telaInicial: class extends self.ISpriteInstance {},
	botaojogar: class extends self.ISpriteInstance {},
	quadro: class extends self.ISpriteInstance {},
	clicarporcos: class extends self.ISpriteInstance {},
	botaovoltar: class extends self.ISpriteInstance {},
	quadro5: class extends self.ISpriteInstance {},
	clicarvacas: class extends self.ISpriteInstance {},
	clicarpescador: class extends self.ISpriteInstance {},
	clicarregador: class extends self.ISpriteInstance {},
	clicarbeberagua: class extends self.ISpriteInstance {},
	quadro6: class extends self.ISpriteInstance {},
	clicarcrianças: class extends self.ISpriteInstance {},
	quadro8: class extends self.ISpriteInstance {},
	porco2: class extends self.ISpriteInstance {},
	clicarACERTOU: class extends self.ISpriteInstance {},
	clicarERROU: class extends self.ISpriteInstance {},
	porcoACERTOU: class extends self.ISpriteInstance {},
	porcoERROU: class extends self.ISpriteInstance {},
	vaca2: class extends self.ISpriteInstance {},
	vacaACERTOU: class extends self.ISpriteInstance {},
	vacaERROU: class extends self.ISpriteInstance {},
	pescador2: class extends self.ISpriteInstance {},
	pescadorACERTOU: class extends self.ISpriteInstance {},
	pescadorERROU: class extends self.ISpriteInstance {},
	planta: class extends self.ISpriteInstance {},
	plantaACERTOU: class extends self.ISpriteInstance {},
	plantaERROU: class extends self.ISpriteInstance {},
	agua: class extends self.ISpriteInstance {},
	aguaACERTOU: class extends self.ISpriteInstance {},
	aguaERROU: class extends self.ISpriteInstance {},
	criancas: class extends self.ISpriteInstance {},
	criancasACERTOU: class extends self.ISpriteInstance {},
	criancasERROU: class extends self.ISpriteInstance {},
	Texto_Acao: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	botaosair: class extends self.ISpriteInstance {},
	Navegador: class extends self.IInstance {},
	botaoinfo: class extends self.ISpriteInstance {},
	buttonMaker: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	EXCLAMAÇÃO1: class extends self.ITextInstance {},
	EXCLAMAÇÃO2: class extends self.ITextInstance {},
	EXCLAMAÇÃO3: class extends self.ITextInstance {},
	EXCLAMAÇÃO4: class extends self.ITextInstance {},
	EXCLAMAÇÃO5: class extends self.ITextInstance {},
	EXCLAMAÇÃO6: class extends self.ITextInstance {},
	teste: class extends self.ITextInstance {}
}